Repository ucsb-cs156-w24/proj-courses-w24-5pm-3, pull requests merged in 2024-03, with the labels that each got.

#18 Fixed "BUG: Can't immediately search for graduate courses"
  frontend/src/main/components/BasicCourseSearch/BasicCourseSearchForm.js
  frontend/src/main/components/Levels/SingleLevelDropdown.js
  frontend/src/tests/components/Levels/SingleLevelDropdown.test.js
  src/main/resources/application.properties
Labels: 10 points

#13 Removed unnecessary exclamation point
  frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
  frontend/src/tests/pages/CourseDetails/CourseDetailsIndexPage.test.js
Labels: 5 points

#21 FEATURE: Add edit page for personal schedules
  .gitignore
  frontend/.storybook/main.js
  frontend/.storybook/preview.js
  frontend/.storybook/webpack-plugin-fail-build-on-warning.js
  frontend/src/index.css
  frontend/src/main/components/PersonalSections/PersonalSectionsEditTable.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesEditPage.js
  frontend/src/main/utils/CoursesEditUtils.js
  frontend/src/stories/components/Jobs/JobsTable.stories.mdx
  frontend/src/stories/components/Jobs/TestJobForm.stories.mdx
  frontend/src/stories/components/Utils/Plaintext.stories.mdx
  frontend/src/tests/components/PersonalSections/PersonalSectionsEditTable.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesEditPage.test.js
  frontend/src/tests/utils/CoursesEditUtils.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/main/resources/application.properties
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 20 points

#19 FEATURE: Add link to developer/GH info in Admin dropdown
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5 points

#17 Created missing stories for PSCourse Pages
  frontend/src/stories/components/Courses/CourseTable.stories.js
  frontend/src/stories/pages/HomePage/Courses/PSCourseCreatePage.stories.js
  frontend/src/stories/pages/HomePage/Courses/PSCourseIndexPage.stories.js
Labels: 10 points

#22 FEATURE: Added frontend for job to update courses by range of quarters
  frontend/src/main/components/Jobs/UpdateCoursesForRangeOfQuartersJobForm.js
  frontend/src/main/pages/AdminJobsPage.js
  frontend/src/stories/components/Jobs/UpdateCoursesForRangeOfQuarters.stories.js
  frontend/src/tests/components/Jobs/UpdateCoursesForRangeOfQuartersJobForm.test.js
  frontend/src/tests/pages/AdminJobsPage.test.js
Labels: 10 points

#26 Created new branch without all of the stryker files finishing course description
  frontend/src/main/components/CourseDetails/CourseDescriptionComponent.js
  frontend/src/main/pages/CourseDetails/CourseDetailsIndexPage.js
  frontend/src/tests/components/CourseDetails/CourseDescriptionComponent.test.js
Labels: 10 points

#20 FEATURE: made storke tower a home button
  frontend/src/main/components/Nav/AppNavbar.js
Labels: 5 points

#31 Add missing stories for CourseForm and PersonalSchedulesDetailsPage
  frontend/src/stories/components/Courses/CourseForm.stories.js
  frontend/src/stories/pages/HomePage/PersonalSchedules/PersonalSchedulesDetailsPage.stories.js
Labels: 10 points

#32 BUG fix: Deleting a personal schedule doesn't delete associated PSCourses
  src/main/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesController.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PersonalSchedulesControllerTests.java
Labels: 20 points

#33 Refactor: Moved page links from Navbar into pages
  frontend/src/main/components/Nav/AppNavbar.js
  frontend/src/main/pages/PersonalSchedules/PersonalSchedulesIndexPage.js
  frontend/src/tests/components/Nav/AppNavbar.test.js
  frontend/src/tests/pages/PersonalSchedules/PersonalSchedulesIndexPage.test.js
Labels: 10 points

#34 FEATURE: Add sections to personal schedule directly from search
  frontend/src/main/components/Sections/SectionsTable.js
  frontend/src/main/components/SectionsTableBase.js
  frontend/src/main/utils/useBackend.js
  frontend/src/tests/components/Sections/SectionsTable.test.js
Labels: 20 points, FIXME - Peer CR

#29 Add more descriptive personal course page
  frontend/src/fixtures/pscourseFixtures.js
  frontend/src/main/components/Courses/CourseTable.js
  frontend/src/tests/components/Courses/CourseTable.test.js
  src/main/java/edu/ucsb/cs156/courses/controllers/PSCourseController.java
  src/main/java/edu/ucsb/cs156/courses/entities/PSCourse.java
  src/test/java/edu/ucsb/cs156/courses/controllers/PSCourseControllerTests.java
Labels: 10 points, merge candidate
